# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7be98b753825c4265ece0fe59fe63ec1eae6ece37de06b4a861ee873e8dd9dbb9a36b99391a424dc970b0b27055d2d4dfb164ce89e43d0ece1b1b0601a68afa2

test:
  secret_key_base: 43830ac943dabf4ca672ce0a5eeab99c7937b1727c8b8a4ac457553e459e78aee40020690953039234d8da978bfd12e208edb59f696835a59b45f1a68d784773

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
